<div class="footList">
<h3>Information for</h3>
<ul>
<li><a href="http://www.sjsu.edu/alumni_and_community/index.html">Alumni</a></li>
<li><a href="http://www.sjsu.edu/students/">Current Students</a></li>
<li><a href="http://www.sjsu.edu/giving/">Donors</a></li>
<li><a href="http://www.sjsu.edu/faculty_and_staff/index.html">Faculty &amp; Staff</a></li>
<li><a href="http://www.sjsu.edu/future_students/index.html">Future Students</a></li>
<li><a href="http://www.sjsu.edu/discover/research/index.html">Researchers</a></li>
</ul>
</div>
<div class="footList">
<h3>Colleges</h3>
<ul>
<li><a href="http://www.sjsu.edu/casa/">Applied Sciences &amp; Arts</a></li>
<li><a href="http://www.sjsu.edu/cob/">Business</a></li>
<li><a href="http://www.sjsu.edu/education/">Education</a></li>
<li><a href="http://engineering.sjsu.edu/">Engineering</a></li>
<li><a href="http://www.sjsu.edu/humanitiesandarts/">Humanities &amp; the Arts</a></li>
<li><a href="http://www.sjsu.edu/cies/">International &amp; Extended Studies</a></li>
<li><a href="http://www.sjsu.edu/science/">Science</a></li>
<li><a href="http://www.sjsu.edu/socialsciences/">Social Sciences</a></li>
</ul>
</div>
<div class="footList">
<h3>Quick Links</h3>
<ul>
<li><a href="http://www.sjsu.edu/siteindex">A-Z Index</a></li>
<li><a href="http://www.sjsu.edu/discover/academics/index.html">Academics</a></li>
<li><a href="http://www.spartanbookstore.com/">Bookstore</a></li>
<li><a href="{{f:1453005}}">Budget Central</a></li>
<li><a href="http://www.sjsu.edu/calendars/index.html">Calendars</a></li>
<li><a href="https://sjsu.instructure.com/">Canvas</a></li>
<li><a href="http://www.sjsu.edu/employment">Careers &amp; Jobs</a></li>
<li><a href="http://library.sjsu.edu/"> King Library</a></li>
<li><a href="http://www.sjsu.edu/parkingtransportationmaps/index.html">Parking &amp; Maps</a></li>
</ul>
</div>
<div class="footList">
<h3>Contact us</h3>
<ul>
<li><a href="http://www.sjsu.edu/contact/index.html">Contact Form</a></li>
<li><a href="http://directory.sjsu.edu">Directory</a></li>
<li><a href="http://go.sjsu.edu/redesign-feedback2" target="_blank">Report A Web Problem</a></li>
</ul>
</div>
<div class="footAddress">
<p><a href="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=San+Jose+State+University,+San+Jose,+CA&amp;sll=37.0625,-95.677068&amp;sspn=51.04407,85.341797&amp;ie=UTF8&amp;hq=San+Jose+State+University&amp;hnear=San+Jose+State+University,+San+Jose,+Santa+Clara,+California+95112&amp;z=15&amp;iwloc=A">One Washington Square,<br /> San Jose, CA 95192</a></p>
<p>408-924-1000</p>
<span id="directedit">&nbsp;</span>
<p class="copyright">©2013</p>
</div>
