<h1 class="acc">Footer Navigation</h1>
<ul id="globalnav">
<li><a href="http://www.sjsu.edu/discover/index.html">Discover</a></li>
<li><a href="http://www.sjsu.edu/future_students/index.html">Future Students</a></li>
<li><a href="http://www.sjsu.edu/students/">Current Students</a></li>
<li><a href="http://www.sjsu.edu/faculty_and_staff/index.html">Faculty &amp; Staff</a></li>
<li><a href="http://www.sjsu.edu/alumni_and_community/index.html">Alumni &amp; Community</a></li>
<li style="line-height: 2em;">|</li>
<li><a href="{{f:1453005}}">Budget Central</a></li>
<li><a href="http://www.sjsu.edu/giving/">Make A Gift</a></li>
<li class="clear"><a href="http://www.sjsu.edu/siteindex">A-Z Index</a></li>
<li><a href="http://www.sjsu.edu/discover/academics/index.html">Academics</a></li>
<li><a href="http://www.spartanbookstore.com/">Bookstore</a></li>
<li><a href="http://www.sjsu.edu/calendars/index.html">Calendars &amp; Events</a></li>
<li><a href="http://www.sjsu.edu/employment">Employment &amp; Careers</a></li>
<li><a href="http://directory.sjsu.edu">Directory</a></li>
<li><a href="http://library.sjsu.edu/">King Library</a></li>
<li><a href="http://www.sjsu.edu/parkingtransportationmaps/index.html">Parking, Transportation &amp; Maps</a></li>
</ul>
<div></div>
<br /> <br />
<div class="left">©2013 SJSU<br /> <a href="http://go.sjsu.edu/redesign-feedback2" target="_blank">Report a problem with this website</a><br /><span id="directedit">&nbsp;</span></div>
<div class="right">
<div class="right"><a class="btn_logo_f" href="http://www.sjsu.edu/"><img src="http://www.sjsu.edu/assets/images/btn_logo_footer_only.gif" alt="SJSU Logo" /></a> <a href="http://sjsu.edu"> San Jose State University<br /> One Washington Square,<br /> San Jose, CA 95192<br /> 408-924-1000</a><br /> <br /><a href="http://www.sjsu.edu/contact/index.html">Contact Us</a></div>
</div>
