<div class="homepagequicklinks">
<ul>
<li><a href="http://www.sjsu.edu/siteindex/">A-Z Index</a></li>
<li><a href="http://www.sjsu.edu/academics/index.html">Academics</a></li>
<li><a href="http://www.spartanbookstore.com">Bookstore</a></li>
<li><a href="http://www.sjsu.edu/calendars/index.html">Calendars</a></li>
<li><a href="http://www.sjsu.edu/employment/index.html">Careers</a></li>
<li><a href="http://directory.sjsu.edu">Directory</a></li>
<li><a href="http://library.sjsu.edu">King Library</a></li>
<li><a href="http://www.sjsu.edu/parkingtransportationmaps/">Parking &amp; Maps</a></li>
</ul>
</div>
