<ul id="homenav">
<li class="discover-sjsu selected"><a href="http://www.sjsu.edu/discover/index.html">
<h2 class="navname">Discover SJSU</h2>
<span class="navarrow">&nbsp;</span></a>
<div class="sub">
<ul>
<li><a class="linkt" href="http://www.sjsu.edu/about_sjsu/">About SJSU</a></li>
<li><a href="http://www.sjsu.edu/academics/">Academics</a></li>
<li><a href="http://www.sjsu.edu/discover/administration/index.html">Administration &amp; Leadership</a></li>
<li><a class="linkb" href="http://www.sjsuspartans.com/">Athletics</a></li>
<li><a href="http://www.sjsu.edu/calendars/">Calendars &amp; Events</a></li>
<li><a href="http://www.sjsu.edu/discover/initiatives/index.html">Initiatives &amp; Partnerships</a></li>
<li><a href="http://library.sjsu.edu/">King&nbsp;Library</a></li>
<li><a href="http://blogs.sjsu.edu/today/">News</a></li>
<li><a href="http://www.sjsu.edu/discover/research/index.html">Research</a></li>
<li><a href="http://www.sjsu.edu/about_sjsu/visiting/">Visit SJSU</a></li>
</ul>
</div>
</li>
<li class="future-students"><a href="http://www.sjsu.edu/future_students/index.html">
<h2 class="navname">Future Students</h2>
<span class="navarrow">&nbsp;</span></a>
<div class="sub">
<ul>
<li><a href="http://my.sjsu.edu/">MySJSU</a></li>
<li><a class="linkt" href="http://www.sjsu.edu/academics/">Academics</a></li>
<li><a class="linkb" href="http://info.sjsu.edu/home/admission.html">Admissions</a></li>
<li><a href="http://www.sjsu.edu/calendars/index.html">Calendars &amp; Events</a></li>
<li><a href="http://www.sjsu.edu/finances/index.html">Finances</a></li>
<li><a href="http://www.sjsu.edu/housingoptions/index.html">Housing Options</a></li>
<li><a href="http://www.sjsu.edu/students/new/index.html">New Students</a></li>
<li><a href="http://www.sjsu.edu/about_sjsu/visiting/index.html">Visit SJSU</a></li>
</ul>
</div>
</li>
	<li class="current-students"><a href="http://www.sjsu.edu/students/index.html">
<h2 class="navname">Current Students</h2>
<span class="navarrow">&nbsp;</span></a>
<div class="sub">
<ul class="focus">
<li><a href="http://my.sjsu.edu/">MySJSU</a></li>
<li><a href="http://www.sjsu.edu/academics/">Academics</a></li>
<li><a href="http://www.sjsu.edu/advising/">Advising</a></li>
<li><a href="http://www.sjsu.edu/calendars/">Calendars &amp; Events</a></li>
<li><a href="http://www.sjsu.edu/students/campuslife/">Campus Life</a></li>
<li><a href="http://www.sjsu.edu/finances/index.html">Finances</a></li>
<li><a href="http://www.sjsu.edu/commencement/graduates/">Graduation</a></li>
<li><a href="http://www.sjsu.edu/students/healthandsafety/index.html">Health &amp; Safety</a></li>
<li><a href="http://library.sjsu.edu">King Library</a></li>
<li><a href="http://www.sjsu.edu/students/new/index.html">New Students</a></li>
<li><a href="http://www.sjsu.edu/students/technologyandmeeting/index.html">Technology &amp; Meetings</a></li>
</ul>
</div>
</li>
<li class="faculty-staff"><a href="http://www.sjsu.edu/faculty_and_staff/index.html">
<h2 class="navname">Faculty &amp; Staff</h2>
<span class="navarrow">&nbsp;</span></a>
<div class="sub">
<ul>
<li><a href="http://my.sjsu.edu">MySJSU</a></li>
<li><a href="http://www.sjsu.edu/academics/">Academics</a></li>
<li><a href="http://www.sjsu.edu/calendars/index.html">Calendars &amp; Events</a></li>
<li><a href="http://www.sjsu.edu/employment/index.html">Employment &amp; Career</a></li>
<li><a href="http://directory.sjsu.edu">Directory</a></li>
<li><a href="http://www.sjsu.edu/faculty_and_staff/healthandsafety/index.html">Health &amp; Safety</a></li>
<li><a href="http://library.sjsu.edu">King Library</a></li>
<li><a href="http://www.sjsu.edu/discover/research/resources/index.html">Research</a></li>
<li><a href="http://www.sjsu.edu/faculty_and_staff/technologyandmeeting/index.html">Technology &amp; Meetings</a></li>
</ul>
</div>
</li>
<li class="alumni-community"><a href="http://www.sjsu.edu/alumni_and_community/index.html">
<h2 class="navname">Alumni &amp; Community</h2>
<span class="navarrow">&nbsp;</span></a>
<div class="sub">
<ul>
<li><a href="http://www.sjsualumni.com/">Alumni Association</a></li>
<li><a href="http://www.sjsu.edu/employment/index.html">Employment &amp; Career</a></li>
<li><a href="http://www.sjsu.edu/biz/index.html">Do Business with SJSU</a></li>
<li><a href="http://www.sjsu.edu/giving/index.html">Give to SJSU</a></li>
<li><a class="linkb" href="http://www.sjsu.edu/careercenter/employers/index.html">Hire SJSU Talent</a></li>
<li><a href="http://www.sjsu.edu/hr/work_life/community/living/volunteer/">Volunteer</a></li>
<li><a href="http://www.sjsu.edu/about_sjsu/visiting/index.html">Visit SJSU</a></li>
</ul>
</div>
</li>
</ul>
