<!-- LIGHTBOX -->
<link rel="stylesheet" type="text/css" href="/sjsuhome/assets/css/jquery.lightbox-0.5.css" media="screen" />

<!-- NIVO SLIDER -->
<link rel="stylesheet" type="text/css" href="/sjsuhome/assets/css/nivo-slider-em.css" media="screen" />
<link rel="stylesheet" type="text/css" href="/sjsuhome/assets/css/nivo-slider-em-test.css" media="screen" />

<!-- ALL STYLES -->
<link rel="stylesheet" type="text/css" href="/sjsuhome/assets/css/testcss.css" media="screen" />
<link rel="stylesheet" type="text/css" href="/sjsuhome/assets/css/printtest.css" media="print" />

<!-- TOOLTIP -->
<link rel="stylesheet" type="text/css" href="/sjsuhome/assets/css/tipTip.css" media="screen" />

<!-- IE COMPATIBILITY -->
<!--[if lt IE 9]>
<link rel="stylesheet" href="/sjsuhome/assets/css/styles-ie.css" />
<script src="sjsuhometest/html5-min.js"></script>
<![endif]-->

<!--[if lte IE 6>
<link rel="stylesheet" href="/sjsuhome/assets/css/updateie6.css" type="text/css" />
<![endif]-->

<!--[if lt IE 7>
<link href="ie6.css" rel="stylesheet" type="text/css" />
<![endif]-->

