<!-- LIGHTBOX -->
<script type="text/javascript" src="/sjsuhometest/assets/js/jquery.lightbox-0.5-min.js"></script>
<!-- NIVO SLIDER -->
<script type="text/javascript" src="/sjsuhometest/assets/js/jquery.nivo.slider.pack-min.js"></script>
<script type="text/javascript">// <![CDATA[
	$(window).load(function() {
	    $('#slider').nivoSlider({
	    effect:'fade',
		pauseTime:6000,
		directionNav:true,
		captionOpacity: 1.0
		});
	});
// ]]></script>
<script type="text/javascript">// <![CDATA[
	$(function() {
		$('#gallery a').lightBox({fixedNavigation:true});
	});
// ]]></script>
<!-- SECONDARY NAV EXPAND -->
<script type="text/javascript" src="/sjsuhometest/assets/js/jquery.navexpand-min.js"></script>
<!-- SCROLLTO -->
<script type="text/javascript" src="/sjsuhometest/assets/js/jquery.scrollTo-1.4.2-min.js"></script>
<script type="text/javascript" src="/sjsuhometest/assets/js/jquery.localscroll-1.2.7-min.js"></script>
<!-- SHARETHIS -->
<script type="text/javascript">// <![CDATA[
var switchTo5x=true;
// ]]></script>
<script type="text/javascript" src="/sjsuhometest/assets/js/buttons-min.js"></script>
<script type="text/javascript">// <![CDATA[
    stLight.options({
        publisher: '12345',
        onhover: false
    });
// ]]></script>
<!-- TOGGLE FIELD VALUE -->
<script type="text/javascript" src="/sjsuhometest/assets/js/jquery.toggleval-min.js"></script>
<!-- HOVERINTENT: MEGANAV -->
<script type="text/javascript" src="/sjsuhometest/assets/js/jquery.hoverIntent-min.js"></script>
<script type="text/javascript" src="/sjsuhometest/assets/js/jquery.meganav-min.js"></script>
<!-- TOOLTIP -->
<script type="text/javascript" src="/sjsuhometest/assets/js/jquery.tipTip-min.js"></script>
<!--[if lte IE 6]>
<script src="/sjsuhometest/assets/js/updateie6-min.js" type="text/javascript"></script>
<![endif]--> <!-- SEARCH AS YOU TYPE -->
<script type="text/javascript" src="/sjsuhometest/assets/js/search-as-you-type-min.js"></script>
<script type="text/javascript">// <![CDATA[
      searchAsYouType.initialize(document.getElementById('q'), false);
// ]]></script>
