<!-- JQUERY -->
<script src="/sjsuhome/assets/js/jquery-1.6.1.min.js" type="text/javascript"></script>
<!-- Side Navigation -->
<script type="text/javascript" src="/sjsuhometest/assets/js/ou-sidenav-min.js"></script>
<!-- Login Link -->
<script type="text/javascript" src="/sjsuhometest/includes/directedit-min.js"></script>
<script type="text/javascript">
  document.ready = function(){ directedit(); }
</script>
	
