<form id="search_home" action="http://search.calstate.edu/search" method="get" name="seek1">
	<input type="hidden" name="x" value="12" />
	<input type="hidden" name="y" value="12" />
	<input type="hidden" name="access" value="p" />
	<input type="hidden" name="site" value="sjsu" />
	<input type="hidden" name="output" value="xml_no_dtd" />
	<input type="hidden" name="client" value="sjsu-v5" />
	<input type="hidden" name="sort" value="date%3AD%3AL%3Ad1" />
	<input type="hidden" name="proxystylesheet" value="sjsu-v5" />
	<input type="hidden" name="oe" value="UTF-8" />
	<label for="q">Search SJSU</label>
	<input id="q" class="typeaheadsjsu populate" title="Search SJSU" type="text" name="q" placeholder="Search SJSU" size="15" maxlength="100" /> 
	<button id="search_submit" class="btnSearch" type="submit" name="submit" >Search</button>
</form>
